### ISSUE TITLE
float: left on field labels breaks editor layout

### ISSUE THREAD

**Issue by jameysharp** [jaap3/django-richtextfield#21] opened 2020-07-31 02:34 UTC
First I just want to say that after getting quite frustrated with all the other Django rich-text apps I tried, this one was refreshingly unopinionated and didn't get in the way of what I needed to do. Thanks for writing it!

I have a layout issue using `RichTextField` in the admin with CKEditor: the CKEditor toolbar is pushed to the right by the field label, but the editable area falls below and is the full available width. Because the toolbar and editable area don't line up, the result looks weird.

I think the `<div class="fieldBox">` which `RichTextWidget.render` wraps around the `<textarea>` tag isn't working quite as intended, but I'm not sure what the right way to fix it is. In particular I couldn't understand the relevant CSS well enough to figure out why the `<label>`, which is outside the `fieldBox`, is affecting layout of things inside of it. This is why I usually stick to backend dev&hellip;

I'm using Django 3.0, django-richtextfield 1.6, and a customized build of CKEditor 4.14.1.

My current workaround is code like this in an `AppConfig` subclass in my project:

```python
    def ready(self):
        import djrichtextfield.widgets
        djrichtextfield.widgets.RichTextWidget.CONTAINER_CLASS += " clear"
```

This changes the wrapper element to `<div class="fieldBox clear">` which ensures that the entire field lands below the `float: left` field label, rather than partially to the right of it.

**Comment by jaap3** [comment] 2020-08-03 08:31
Thanks for the kind words! I haven't seen this issue myself and pretty much use the same setup as you (CKEditor 4.x in the Django 3 admin). I'll see if I can find some time to look into it.

Would you mind posting a screenshot here that shows the layout issue?

**Comment by jameysharp** [comment] 2020-08-03 16:49
Oh, good point! Here's a screenshot:

![ckeditor-layout-issue](https://user-images.githubusercontent.com/865272/89202652-24446a80-d568-11ea-8e53-933ac6fbacd2.png)

By contrast:

![ckeditor-layout-workaround](https://user-images.githubusercontent.com/865272/89204997-d92c5680-d56b-11ea-88bb-4fbcf7a862a1.png)

I would be just as happy with the entire editor staying to the right of the label like the stock `Textarea` widget does. It doesn't have to be full-width below the label.

Since the workaround gets me results I'm happy with, I'm in no rush for a proper fix. Just thought I'd bring it up in case anybody else runs into it.

In case any of the rest of my setup makes a difference, here's the outline of my code. I'm configuring `djrichtextfield` this way:

```python
DJRICHTEXTFIELD_CONFIG = {
    "js": [f"{STATIC_URL}ckeditor/ckeditor.js"],
    "init_template": "djrichtextfield/init/ckeditor.js",
    "settings": …,
    "profiles": …,
    "sanitizer_profiles": …,
}
```

I placed `STATIC_URL` in there explicitly to bypass `CompressedManifestStaticFilesStorage` because I didn't want to figure out how to set `CKEDITOR_BASEPATH`. And I've elided the ckeditor and sanitizer configuration because commenting it all out doesn't change this.

The model is trivial:

```python
class Report(models.Model):
    …
    notes = RichTextField(field_settings="…")
```

I'm using this in a `StackedInline` rather than a `ModelAdmin`, but I just tested the same model with a default `ModelAdmin` (`admin.site.register(models.Report)`) and got the same behavior.

```python
class ReportInline(admin.StackedInline):
    model = models.Report
    extra = 1
```

**Comment by jaap3** [comment] 2020-08-06 12:50
I tried reproducing it, but am unable to. Using CKEditor 4.14.1 (//cdn.ckeditor.com/4.14.1/standard/ckeditor.js) the field is properly aligned (both in inlines and normal admin pages):

![Screenshot 2020-08-06 at 14 46 14](https://user-images.githubusercontent.com/48517/89533395-a5fbf880-d7f3-11ea-9783-922174e234b7.png)

Maybe your custom build is using a different skin that is causing the layout issue you are seeing. Since you have a workaround and I don't think I can provide a generic fix I'm closing this issue.

**Closed by jaap3** 2020-08-06 12:50 UTC

**Comment by zopagaduanjr** [comment] 2020-08-11 12:57
![image](https://user-images.githubusercontent.com/38291023/89899416-d937f080-dc14-11ea-9869-c873ab93808c.png)
I also encounter this alignment issue, but I don't know how I got it, using django 2.1.10 & richtext==1.6


```
DJRICHTEXTFIELD_CONFIG = {
    'js': ['//cdn.ckeditor.com/4.14.1/standard/ckeditor.js'],
    'init_template': 'djrichtextfield/init/ckeditor.js',

}
```
